export const GAME_ACTIONS = {
  RESET_VOTED_PLAYERS: 'RESET_VOTED_PLAYERS',
  CHANGE_VOTED_PLAYERS: 'CHANGE_VOTED_PLAYERS',
  ADD_PLAYER_ON_VOTE: 'ADD_PLAYER_ON_VOTE',
  SET_COUNT_OF_PLAYERS: 'SET_COUNT_OF_PLAYERS',
  CHANGE_PLAYERS: 'CHANGE_PLAYERS',
} as const;