export const ADD_PLAYER_ON_VOTE = 'ADD_PLAYER_ON_VOTE';
export const SET_COUNT_OF_PLAYERS = 'SET_COUNT_OF_PLAYERS';
export const CHANGE_PLAYERS = 'CHANGE_PLAYERS';
export const CHANGE_VOTED_PLAYERS = 'CHANGE_VOTED_PLAYERS';
export const RESET_VOTED_PLAYERS = 'RESET_VOTED_PLAYERS';
